Map<String, String> enUs = {
  'hello_world': 'Holle World',
  'about_us': 'About us',
  'text':
      'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using "Content here, content here", making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for "lorem ipsum" will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).',
  'v.1.2': 'v.1.2',
  'up_date': 'up date',
  'send_feedback': 'send  feed back',
  'learn_how_we_work': 'Learn how we work',
  'share_us': 'Share US',
  'profile_name': 'aziz shrafi',
  'email': 'testemail@gmail.com',
  'my_order': 'My Order',
  'favorite': 'Favorite',
  'my_profile': 'My Profile',
  'delivary_addres': 'Delivary addres',
  'payment_method': 'Payment method',
  'vouchers_credit': 'Vouchers & credit',
  'notifications': 'Notifications',
  'contact_us': 'contact us',
  'logout': 'Logout',
  'contact-us': 'Contact us',
  'welcome': 'Welcome',
  'send_us_email': 'send us Email',
  'user_name': 'user name',
  'mobile': 'mobile',
  '_email': 'Email',
  '_text': 'text',
  'send': 'SEND',
};
